### ISSUE TITLE
Add Branch Reconciliation Guidelines to Contributing.md

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/.github#4]
In projects with multiple contributors, branches often diverge due to parallel development. Clear guidelines on how to reconcile these branches (using merge or rebase strategies) will ensure consistency and clarity in collaboration.

Without standardized procedures, contributors might use different methods to integrate changes, leading to unnecessary conflicts and complications. Providing a standard approach will help in avoiding such issues.

## Merge vs rebase
On shared branches, merging is often preferred. It avoids rewriting history, which can be problematic for others working on the same branch.

Rebasing before making a pull request can clean up your history, making it easier for maintainers to understand your changes.

I would recommend Merge since it does not change the existing history.

**Comment by rngadam** [comment]
I'd rather we take the opportunity to clean up the history in the PR with a rebase before merging to the main. It also makes it easier to ensure conflicts have been properly resolved.
